Changes to allow downloading images via feature toggle.
melbjvm/nametags pull request #10
Opened 2017-04-30 10:25 UTC by tfindlay-au

2017-04-30 12:08 UTC, neversleepz requested changes
Hi Tim,
Thanks for doing the changes.  Big help to the project overall.  
I've got a couple of small refactors to suggest.
Cheers.

2017-04-30 12:08 UTC, neversleepz commented on src/main/java/io/github/linead/nametags/domain/Attendee.java
> +            return null;
Return an empty string instead of null

2017-04-30 12:08 UTC, neversleepz commented on src/main/java/io/github/linead/nametags/domain/Attendee.java
> +    public void setPictureUrl(String pictureUrl) { this.pictureUrl = pictureUrl; }
Can you change the setters and getters to be across 3 lines (and the setPictureData below)?

2017-04-30 12:08 UTC, neversleepz commented on src/main/java/io/github/linead/nametags/Nametags.java
> +                    log.warn("No image for:" + rsvp.getMember().getName());
Take these 2 lines and extract them into a separate method for readability
setImageToMelbJVMLogoWhenNoPictureSet();

2017-04-30 12:08 UTC, neversleepz commented on src/main/java/io/github/linead/nametags/Nametags.java
> +                        // Retrieve image data and encode it
Extract to separate private method - that way you can keep all the error handling logging in the method.
```
String pictureData = encodeImageData(pictureUrlStr);
att.setPictureData(pictureData);
```

2017-04-30 12:08 UTC, neversleepz commented on src/main/java/io/github/linead/nametags/Nametags.java
> +                            log.error("getAttendeeList() Bad photo URL:" + e.getMessage());
When in these two error branches, can we default to setting the image to the melbjvm logo, encoded in bytes?

2017-04-30 12:08 UTC, neversleepz commented on src/main/java/io/github/linead/nametags/domain/Attendee.java
> +            return null;
... or even [imageUrl:melbjvm default image url]
(that way we can take out the special handling out from Nametags.java#113 that assigns the default url, and the error cases can leave both null)

2017-04-30 12:08 UTC, neversleepz commented on src/main/java/io/github/linead/nametags/Nametags.java
> +                            log.error("getAttendeeList() Bad photo URL:" + e.getMessage());
nevermind, see my comment in Attendee.java
These error cases can just return null

2017-04-30 12:08 UTC, neversleepz commented on src/main/java/io/github/linead/nametags/Nametags.java
> +                            Base64 b64 = new Base64();
There is a static initialiser for Base64 so we dont have to initialise a `new Base64()` for each attendee.
 
`Base64#getEncoder()` or `Base64#getMimeEncoder()` (not sure which one we need)

As Base64 is thread safe, you could even bring this out as a field.

2017-05-01 12:03 UTC, tfindlay-au commented on src/main/java/io/github/linead/nametags/domain/Attendee.java
> +    public void setPictureUrl(String pictureUrl) { this.pictureUrl = pictureUrl; }
I was just keeping the standard. Refer to the other beans. None the less, updated as requested.

2017-05-01 12:04 UTC, tfindlay-au commented on src/main/java/io/github/linead/nametags/domain/Attendee.java
> +            return null;
Great suggestion. Done!

2017-05-01 12:06 UTC, tfindlay-au commented on src/main/java/io/github/linead/nametags/Nametags.java
> +                    log.warn("No image for:" + rsvp.getMember().getName());
Removed the Else clause, the bean will now substitute the default if a value is not supplied.

2017-05-01 12:07 UTC, tfindlay-au commented on src/main/java/io/github/linead/nametags/Nametags.java
> +                            log.error("getAttendeeList() Bad photo URL:" + e.getMessage());
Set it to return the default image. :)

2017-05-01 12:07 UTC, tfindlay-au commented on src/main/java/io/github/linead/nametags/Nametags.java
> +                            Base64 b64 = new Base64();
Yep, I thought about this, but was lazy. now fixed.

2017-05-01 12:17 UTC, tfindlay-au commented on src/main/java/io/github/linead/nametags/Nametags.java
> +                            Base64 b64 = new Base64();
PS. Saved a dependency too as I was using the Apache Common Codec implementation. Now using built-in Java 8 encoder.

2017-05-01 12:19 UTC, tfindlay-au commented on src/main/java/io/github/linead/nametags/Nametags.java
> +                        // Retrieve image data and encode it
Done, see method encodeImageData()

2017-05-01 13:13 UTC, neversleepz commented
Was that the standard, or just intellij's auto folding?

On Mon, May 1, 2017 at 10:03 PM, tfindlay-au <notifications@github.com>
wrote:

> *@tfindlay-au* commented on this pull request.
> ------------------------------
>
> In src/main/java/io/github/linead/nametags/domain/Attendee.java
> <https://github.com/melbjvm/nametags/pull/10#discussion_r114119478>:
>
> > @@ -37,11 +42,21 @@ public String getPictureUrl() {
>          return pictureUrl;
>      }
>
> -    public void setPictureUrl(String pictureUrl) {
> -        this.pictureUrl = pictureUrl;
> +    public void setPictureUrl(String pictureUrl) { this.pictureUrl = pictureUrl; }
>
> I was just keeping the standard. Refer to the other beans. None the less,
> updated as requested.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/melbjvm/nametags/pull/10#discussion_r114119478>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AA_E3wQVvuEkUlL3Mqzj9i68Dujt7VA5ks5r1colgaJpZM4NMh8U>
> .
>

2017-05-01 13:14 UTC, neversleepz commented
awesome :)

On Mon, May 1, 2017 at 10:17 PM, tfindlay-au <notifications@github.com>
wrote:

> *@tfindlay-au* commented on this pull request.
> ------------------------------
>
> In src/main/java/io/github/linead/nametags/Nametags.java
> <https://github.com/melbjvm/nametags/pull/10#discussion_r114120143>:
>
> >              //get member
>              Members.Member member = members.get(rsvp.getMember().getMember_id());
>              if(member != null) {
>                  att.setJoined(member.getJoined());
>                  if(member.getPhoto() != null) {
> -                    att.setPictureUrl(member.getPhoto().getThumb_link());
> +
> +                    String pictureURLStr = member.getPhoto().getThumb_link();
> +                    log.info("getAttendeeList() photo URL:" + pictureURLStr);
> +
> +                    if(sendPictureAsBase64) {
> +                        // Retrieve image data and encode it
> +                        try {
> +                            byte[] b = IOUtils.toByteArray((new URL(pictureURLStr)).openStream());
> +                            Base64 b64 = new Base64();
>
> PS. Saved a dependency too as I was using the Apache Common Codec
> implementation. Now using built-in Java 8 encoder.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/melbjvm/nametags/pull/10#discussion_r114120143>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AA_E3x4L8IDLX5L0xB804e8y6_q3AluGks5r1c1JgaJpZM4NMh8U>
> .
>

2017-05-01 13:27 UTC, neversleepz approved these changes
Ok good stuff

2017-05-01 13:27 UTC, merged